Attempt to add new services for MAUI SoilMapp.
APSIMInitiative/APSoil pull request #9
Opened 2024-03-08 03:12 UTC by zur003

@hol353 - I think these small changes should enable the additional services I need for the MAUI version of SoilMapp, but I'm not in a position to actually test whether it works. Also I don't know much about setting up web services, so I'm not sure whether the Reference.cs and Service.wsdl stuff gets updated automatically, or whether I need to modify them as well.

2024-04-01 22:49 UTC, hol353 commented
@par456 or @ric394 Can you get this merged and get dev.apsim.info updated? The problem will be trying to compile this as it uses .NET framework 4.6.1 I think. It also wants to compile bits of APSIM 7.10. I think instead it should just link to the assemblies which we can commit to the repo.

2024-04-01 22:53 UTC, hol353 commented
[Apsim710Binaries.zip](https://github.com/APSIMInitiative/APSoil/files/14829268/Apsim710Binaries.zip)

2024-04-02 22:28 UTC, ric394 commented on WebService/Service.asmx.cs
>              //StreamWriter Out = new StreamWriter("D:\\Websites\\FILES\\Transfer\\ApsoilWeb.txt", true);
Commented code needs removing

2024-04-02 22:29 UTC, ric394 requested changes
Just need comments to be removed. Everything else looks good.

2024-04-12 03:57 UTC, ric394 approved these changes

2024-04-12 03:57 UTC, merged